config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts do
    resources :comments
  end
  root 'posts#index'
  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'admin/posts' => 'managerposts#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true

  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_friendly_id?
    title_changed?
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.friendly.find(params[:post_id])
      @comment = @post.comments.create(comment_params)
      redirect_to post_path(@post)
  end

  def destroy
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commentname, :body)
    end
end

app/controllers/managerposts_controller.rb
class ManagerpostsController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :body, :description, :urlbanner))
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to :back
  end

  private

    def set_post
      @post = Post.friendly.find(params[:id])
    end
    
    def post_params
      params.require(:post).permit(:title, :body, :description, :urlbanner)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by("LOWER(username) = ?", user_params[:username].downcase)
    if @user.present?
      if @user.password == user_params[:password].downcase
        session[:current_name] = @user.last_name
        session[:current_level] = @user.level
        flash[:notice] = "login successfully"
        redirect_to :controller => 'posts', :action => 'index'
      else
        flash[:notice] = "wrong password"
        redirect_to :back
      end
    else
      flash[:notice] = "username not found"
      redirect_to :back
    end
  end

  def destroy
    session.clear
    redirect_to :back
  end
  
  private
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    if params[:user][:repassword] == params[:user][:password]
      @user = User.new(user_params)
      if @user.save
        flash[:notice] = "Register successfully"
        redirect_to :controller => 'posts', :action => 'index'
      else
        redirect_to :back
      end
    else
      flash[:notice] = "Confirm password wrong"
      redirect_to :back
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :email, :gender, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown content
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true, tables: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
      quote: true,
      highlight: true,
      tables: true,
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/managerposts_helper.rb
module ManagerpostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pagescontroller_helper.rb
module PagescontrollerHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.slim
- if comment.present?
  p.alert.alert-success
    strong Name:
    = comment.commentname
    br
    strong Comment:
    = comment.body
    br
    - if session[:current_level].present? && session[:current_level] == 1
    = link_to 'Delete', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }

app/views/comments/_form.html.slim
= form_for([post, post.comments.build]) do |f|
  p
    = f.label :commentname
    = f.text_field :commentname
  p
    = f.label :body
    = f.text_area :body
  p
    =f.submit "Add comment", :class => "btn btn-info btn-comment"

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      = link_to 'MyBlog', root_path, class: 'navbar-brand'
    ul.nav.navbar-nav
      li
        = link_to 'Home', root_path
      li
        = link_to 'About', about_path
      li
        = link_to 'Contact', contact_path
    ul.nav.navbar-nav.navbar-right
      - if session[:current_name].present?
        li
          = link_to session[:current_name]
        li
          = link_to "logout", logout_path, data: {confirm: 'Are you sure?'}
      - if !session[:current_name].present?
        li
          = link_to "Sign up", users_path
        li
          = link_to "Login", login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = yield(:page_title)
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/navbar"
    .container
      = yield

app/views/managerposts/index.html.slim
table.table
  thead
    tr
      th Create at
      th Title
      th Body
      th Slug
      th
  tbody
    - @posts.each do |post|
      tr
        td = post.created_at
        td = post.title
        td = truncate(post.body, length: 30)
        td = post.slug
        td
          = link_to 'Delete', post, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-primary"
          = link_to "Edit", edit_post_path(post), :class => "btn btn-primary"

app/views/pages/about.html.slim
div about

app/views/pages/contact.html.slim
iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.6703821635447!2d106.68777225096345!3d10.75986669229514!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f10f6722249%3A0xc9413aa148506b4c!2zMzQ1LzEzNCBUcuG6p24gSMawbmcgxJDhuqFvLCBD4bqndSBLaG8sIFF14bqtbiAxLCBI4buTIENow60gTWluaCwgVmlldG5hbQ!5e0!3m2!1sen!2s!4v1516088318258" width="100%" height="600" frameborder="0" style="border:0" allowfullscreen

app/views/posts/_form.html.slim
= form_for(post) do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body, class: "form-control input-md",  placeholder: "your text", id: "markdown"
  .field
    = f.label :description
    = f.text_area :description, class: "form-control input-md"
  .field
    = f.label :urlbanner
    = f.text_field :urlbanner
  .actions
    = f.submit"Create", :class => "btn btn-info"

app/views/posts/edit.html.slim
h1 Editing Post
= render 'form', post: @post
= link_to 'Show', @post, :class => "btn btn-primary"
= link_to 'Back', posts_path, :class => "btn btn-primary"

app/views/posts/index.html.slim
- if flash[:notice]
  h5.noticesuccess = flash[:notice]
- if session[:current_level].present? && session[:current_level] == 1
  = link_to 'New post', new_post_path, type: "button", class: "btn btn-success"
- provide(:page_title, 'Index')
.row
  .col-sm-2
  .col-sm-8
    - @posts.each do |post|
      = link_to post
        .col-sm-12.listgroup
          .card-text.showimg style = "background-image: url('#{post.urlbanner}')"
          .card-text
            h3.card-title = post.title
          .card-text
            = truncate(post.body, length: 500)
          .card-text
            - if session[:current_level].present? && session[:current_level] == 1
              = link_to "Destroy", post, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger"
  .col-sm-2

app/views/posts/new.html.slim
h1 New Post
= render 'form', post: @post
br
= link_to 'Back', posts_path, :class => "btn btn-success"

app/views/posts/show.html.slim
.row
  .col-sm-2
  .col-sm-8
    - provide(:page_title, @post.title)
    p#titlepage
      strong
        = @post.title
    .showimg style = "background-image: url('#{@post.urlbanner}')"
    p
      = @post.body
    p
      = @post.description
    p
      - if session[:current_level].present? && session[:current_level] == 1
        = link_to 'Edit', edit_post_path(@post), :class => "btn btn-primary"
      = link_to 'Back', posts_path, :class => "btn btn-primary"
    p.well
      strong Comment list
    = render @post.comments
    - if session[:current_level].present?
      = render partial: 'comments/form', locals: { post: @post}
  .col-sm-2

app/views/users/index.html.slim
row
  .col-sm-4
  .col-sm-4
    - if flash[:notice]
        h5.noticefail
          = flash[:notice]
    = form_for :user do |f|
      .field
        = f.label :username
        = f.text_field :username, class: "form-control", :required => true
      .field
        = f.label :password
        = f.password_field :password, class: "form-control", :required => true
      .field
        = f.label :repassword
        = f.password_field :repassword, class: "form-control", :required => true
      .field
        = f.label :email
        = f.email_field :email, class: "form-control", :required => true
      .field
        = f.label :gender
        = f.select :gender, options_for_select(['Nam', 'Nu'])
      .field
        = f.label :lastname
        = f.text_field :last_name, class: "form-control", :required => true
      br
      .actions
        = f.submit "Register", :class => "btn btn-info"
  .col-sm-4